account/urls.py
from django.urls import path
from . import views

app_name= 'account'
urlpatterns = [
    path('login', views.login, name='login'),
]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # todoのurls.pyを読み込み
    path('', include('todo.urls')),
    # accountのurls.pyを読み込み
    path('', include('account.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

todo/urls.py
from django.urls import path
from . import views

app_name= 'todo'
urlpatterns = [
    # viewsからindexを読み込んで、nameをindexに
    path('', views.index, name='index'),
    path('<int:pk>', views.todo_detail, name='todo_detail'),
    path('create', views.todo_create, name='todo_create'),
    path('update/<int:pk>', views.todo_update, name='todo_update'),
    path('delete/<int:pk> ', views.todo_delete, name='todo_delete'),
]

account/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models


class Todo(models.Model):

    title = models.CharField('タイトル', max_length=55)
    body = models.TextField('詳細', max_length=200)
    created = models.DateTimeField('作成日時', auto_now_add=True)
    updated = models.DateTimeField('更新日時', auto_now=True)

    def __str__(self):
        return self.title

todo/forms.py
from django import forms

from .models import Todo

class TodoForm(forms.ModelForm):

    class Meta:
        model = Todo
        fields = ('title', 'body')

account/views.py
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm

class LoginView(LoginView):

    template_name = 'account/login.html'
    form_class = AuthenticationForm

login = LoginView.as_view()

todo/views.py
from django.views.generic import (
    ListView, DetailView, CreateView, UpdateView, DeleteView
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from .models import Todo
from .forms import TodoForm


class IndexView(LoginRequiredMixin, ListView):

    template_name = 'index.html'
    model = Todo
    context_object_name = 'todos'

index = IndexView.as_view()


class TodoDetailView(LoginRequiredMixin, DetailView):

    template_name = 'todo/detail.html'
    model = Todo
    context_object_name = 'todo'

todo_detail = TodoDetailView.as_view()


class TodoCreateView(LoginRequiredMixin, CreateView):

    template_name = 'todo/create.html'
    model = Todo
    form_class = TodoForm
    success_url = reverse_lazy('todo:index')

todo_create = TodoCreateView.as_view()


class TodoUpdateView(LoginRequiredMixin, UpdateView):

    template_name = 'todo/update.html'
    model = Todo
    form_class = TodoForm
    success_url = None

    def get_success_url(self):
        success_url = reverse_lazy('todo:todo_detail', kwargs={'pk':self.kwargs['pk']})
        return success_url

todo_update = TodoUpdateView.as_view()


class TodoDeleteView(LoginRequiredMixin, DeleteView):

    template_name = 'todo/delete.html'
    model = Todo
    success_url = reverse_lazy('todo:index')

todo_delete = TodoDeleteView.as_view()

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mypytodo</title>
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/icofont.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/mypytodo.css' %}">
</head>
<body>
    <main class="wrapper bg-gradient">
        {% include 'includes/base/nav.html' %}
        {% block main %}{% endblock %}
        {% include 'includes/base/footer.html' %}
    </main>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/includes/base/footer.html
<footer class="py-3">
    <div class="text-center">
        <span class="text-muted">©︎2021 XXX all rights reserved</span>
    </div>
</footer>

templates/includes/base/nav.html
{% load static %}
<nav class="text-center mb-5">
    <a class="navbar-brand py-4 text-light font-40 font-weight-bold" href="/">MyPyTodo</a>
</nav>
  

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
    <section>
        <div class="container">
            <div class="">
                <div class="row">
                    <div class="col-11 col-sm-9 col-md-8 col-lg-7 mx-auto">
                        {% for todo in todos%}
                        <div class="card rounded-pill mb-2">
                            <div class="container py-2">
                                <div class="row">
                                    <div class="col-10 col-md-9">
                                        <div class="px-3">
                                            <a href="{% url 'todo:todo_detail' todo.id %}" class="todo-title">{{ todo.title }}</a>
                                        </div>
                                    </div>
                                    <div class="col-2 col-md-3">
                                        <div class="text-right px-3">
                                            <a href="{% url 'todo:todo_delete' todo.id %}"><i class="icofont-ui-delete text-pink font-20 text-danger"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="d-inline-block bg-white plus-btn shadow">
                <a href="{% url 'todo:todo_create' %}">
                    <i class="icofont-plus plus-icon text-pink"></i>
                </a>
            </div>
        </div>
    </section>
{% endblock %}

templates/todo/create.html
{% extends 'base.html' %}
{% load static widget_tweaks %}
{% block main %}

<div class="container">
    <form action="" method="post">
        <div>
            <div class="row">
                <div class="col-sm-7 col-md-6 mx-auto">
                    {% render_field form.title class="form-control mb-3 rounded-pill text-dark-light" placeholder="タイトル" %}
                </div>
            </div>
            <div class="row">
                <div class="col-sm-7 col-md-6 mx-auto">
                    {% render_field form.body class="form-control mb-3 rounded text-dark-light" placeholder="詳細" %}
                </div>
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-lg bg-white text-pink shadow border-orange">作成する</button>
            </div>
        </div>
        {% csrf_token %}
    </form>
</div>

{% endblock %}

templates/todo/delete.html
{% extends 'base.html' %}
{% load static %}
{% block main %}

<section>
    <div class="container mb-5">
        <div class="text-center py-2 mb-3">
            <span class="text-white font-20 font-weight-bold">Todoを削除します。よろしいですか？</span>
        </div>
        <div class="row">
            <div class="col-11 col-lg-8 mx-auto mb-3">
                <div class="card border rounded-pill py-3 text-dark-light px-4">
                    <h5 class="mb-0 font-20">タイトル: {{ todo.title }}</h5>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-11 col-lg-8 mx-auto mb-3">
                <div class="card border rounded-pill py-3 text-dark-light px-4">
                    <p class="mb-0 font-20 font-weight-bold">詳細: {{ todo.body|linebreaksbr }}</p>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-6">
                <div class="text-right">
                    <a href="{% url 'todo:index' %}" class="btn bg-lightgrey border-orange text-dark-light shadow">戻る</a>
                </div>
            </div>
            <div class="col-6">
                <div class="text-left">
                    <form action="" method="post">
                        <button type="submit" class="btn bg-white border-orange text-pink shadow">削除する</button>
                        {% csrf_token %}
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/todo/detail.html
{% extends 'base.html' %}
{% load static %}
{% block main %}

<section>
    <div class="container mb-5">
        <div class="row">
            <div class="col-11 col-lg-8 mx-auto mb-3">
                <div class="card border rounded-pill py-3 text-dark-light px-4">
                    <h5 class="mb-0 font-20">タイトル: {{ todo.title }}</h5>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-11 col-lg-8 mx-auto mb-3">
                <div class="card border rounded-pill py-3 text-dark-light px-4">
                    <p class="mb-0 font-20 font-weight-bold">詳細: {{ todo.body|linebreaksbr }}</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-11 col-lg-8 mx-auto mb-3">
                <div class="card border rounded-pill py-3 text-dark-light px-4">
                    <span class="mb-0 font-20 font-weight-bold">作成日時: {{ todo.created|date:'Y/m/d H:i' }}</span>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-6">
                <div class="text-right">
                    <a href="{% url 'todo:index' %}" class="btn bg-lightgrey border-orange text-dark-light shadow">戻る</a>
                </div>
            </div>
            <div class="col-6">
                <div class="text-left">
                    <a href="{% url 'todo:todo_update' todo.id %}" class="btn bg-white border-orange text-pink shadow">編集する</a>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/todo/update.html
{% extends 'base.html' %}
{% load static widget_tweaks %}
{% block main %}

<div class="container">
    <form action="" method="post">
        <div>
            <div class="row">
                <div class="col-sm-7 col-md-6 mx-auto">
                    {% render_field form.title class="form-control mb-3 rounded-pill text-dark-light" placeholder="タイトル" %}
                </div>
            </div>
            <div class="row">
                <div class="col-sm-7 col-md-6 mx-auto">
                    {% render_field form.body class="form-control mb-3 rounded text-dark-light" placeholder="詳細" %}
                </div>
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-lg bg-white text-pink shadow border-orange">更新する</button>
            </div>
        </div>
        {% csrf_token %}
    </form>
</div>

{% endblock %}